# Generated by Django 4.2.7 on 2023-11-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='no-image.png', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('docena', 'Docena'), ('por-kilo', 'Kilo'), ('unitario', 'Precio Unitario'), ('media-doc', 'Media Docena')], default='unitario', max_length=9, verbose_name='Tipo de Precio'),
        ),
    ]
